Add controllers
zg-devj/java-shareit pull request #1
Opened 2023-04-28 17:11 UTC by zg-devj

2023-04-29 17:33 UTC, TomattmanYandex requested changes
ПРивет, выполнено хорошо, но есть мелочи на поправить

2023-04-29 17:33 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
DTO используются не только для запросов но и для ответов, и если хочешь с обьектом передавать данные о тот кто его владелец или запросе, то стоит добавить в него эти поля

2023-04-29 17:33 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestHeader(value = "X-Sharer-User-Id", required = false) Long userId,
параметр должен быть обязательным, иначе как мы его привяжем к конкретному пользователю

2023-04-29 17:33 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestHeader(value = "X-Sharer-User-Id", required = false) Long userId,
это стоит везде исправить

2023-04-29 17:33 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = ItemMapper.toItem(itemDto);
обычно преобразование из дто в обьект происходит на уровне сервисов

2023-04-29 17:33 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryRepository.java
> +    Map<Long, Item> items = new HashMap<>();
модификатор доступа

2023-04-29 17:33 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item updateItem(Long userId, Item item) {
мне кажется тут стоит сделать так как делали уже раньше просто заменой пришедшим обьектом

2023-04-29 17:33 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User user = UserMapper.toUser(userDto);
аналогично что и с фильмами

2023-04-29 18:54 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
Просто , в postman тестах напрямую и в ТЗ  указано что информацию о пользователе не нужно передавать в DTO ItemDto .

2023-04-29 18:57 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
Я понимаю что объект  DTO это сущность которая может передавать любые данные из одной или нескольких сущностей.

2023-04-29 19:00 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestHeader(value = "X-Sharer-User-Id", required = false) Long userId,
Спасибо. Исправил.

2023-04-29 19:13 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = ItemMapper.toItem(itemDto);
Везде где смотрел (не припомню, что бы в теории про это что-то было) преобразование из DTO и обратно используется в контроллере.

https://www.baeldung.com/entity-to-and-from-dto-for-a-java-spring-application
https://www.baeldung.com/java-dto-pattern
https://for-each.dev/lessons/b/-entity-to-and-from-dto-for-a-java-spring-application
https://reflectoring.io/spring-boot-web-controller-test/

Хотя вот здесь в сервисе, но есть и в контроллере. : https://medium.com/learnwithnk/best-practices-in-spring-boot-project-structure-layers-of-microservice-versioning-in-api-cadf62bd3459

Мне кажется нужно смотреть по случаю. 
Как мне кажется  в данном случае не существенно

2023-04-29 19:15 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = ItemMapper.toItem(itemDto);
Хотя при PATCH я бы наверно все таки передавал DTO в сервис слой. Буду смотреть по следующим ТЗ. Хорошо что это обучение и есть возможность взглянуть с разной стороны.

2023-04-29 19:16 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryRepository.java
> +    Map<Long, Item> items = new HashMap<>();
Спасибо. Исправил.

2023-04-29 19:19 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User user = UserMapper.toUser(userDto);
Выше написал.

2023-04-29 19:33 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item updateItem(Long userId, Item item) {
Т.к. по тестам postman и ТЗ мы используем только PATCH, то просто обновить пришедшим объектом не выйдет, т.к. на входе у нас может быть только один параметр обновления.

2023-04-30 15:29 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
окок, принято

2023-04-30 15:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = ItemMapper.toItem(itemDto);
Да, полностьью согласен, может быть в разных местах, но если есть передача дто на слой сервиса то мне кажется лучше для консистентности данных везде на уровне сервиса использовать DTO а после хорошим способом будет перегрузка метода по параметру, и например есть метод который принимает DTO переводит его в обьект и вызывает другой метод именно с этим обьектом

2023-04-30 15:33 UTC, TomattmanYandex approved these changes
Принято

2023-04-30 16:12 UTC, merged