Add bookings
zg-devj/java-shareit pull request #2
Opened 2023-05-18 19:48 UTC by zg-devj

2023-05-19 10:08 UTC, TomattmanYandex requested changes
Привет, коменты как обычно в коде

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static Booking toBooking(BookingNewDto bookingNewDto, Item item, User user) {
почему бы в маппере не назвать методы dtoToObject и objectToDto 
таким образом получится, что по имени класса мы поймем что мапим, а во всех мапперах убуд одинаковые имена,

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static List<BookingDto> toBookingDto(Iterable<Booking> bookings) {
зачем использовать настолько абстрактную версию списка, чаще всего хватает определения на уровне интерфейса например LIst либо Map, если очень надо то переходят к коллекциям, а вот ниже, только если есть конкретная необходимость

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByBooker_IdOrderByStartDesc(Long bookerId);
Очень смущают нижние подчеркивания в методах, не похоже на стиль именования в Java 
Да и спринг должен воспринять нормально и без него

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllBookings(Long userId, State state, boolean isOwner) {
какой длинный метод, 
1) может стоит разбить на методы поменьше
2) на уровне контроллера два разных метода вызывают этот метод с разными параметрами, и в самом методе есть разделение логики из-за этого параметра, лучше сделать два метода в сервисе, один будет возвращать только для владельца, второй только для всех - таким образом и сам метод станет проще, и зоны ответственности станут уже, и меньше всяких ифов будет

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/State.java
> +    public boolean equal(String paramState) {
Это похоже на логику сервиса
да и реализовать можно по другому
у енамов есть метод которые из строки делает обьект этого перечисления
а их можно сравнить через ==

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/StateConverter.java
> +public class StateConverter implements Converter<String, State> {
тоже кажется чем то излишним

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +public class PersistenceConfig {
а зачем этот класс?

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exceptions/ErrorMessage.java
> +    private String error;
обычно в сообщение об ошибке включают две переменные, саму ошибку и сообщение

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +    public static CommentDto toCommentDto(Comment comment) {
то же что и в первом маппере

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> findCommentsByItem_IdOrderByCreatedAsc(Long itemId);
и снова про нижние подчеркивания

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private Set<BookingStatus> getIn() {
зачем этот метод

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<BookingShort> lastList = bookingRepository.getLastBooking(itemId, userId,
не проще ли было бы получить бронирования по айтему и юзеру, отсортированные по дате, и выбрать первый с лимитом в количество записей в 1
Очень неуместным смотрится использование постраничных запросов

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<BookingShort> nextList = bookingRepository.getNextBooking(itemId, userId,
и тут аналогично, постраничные запросы не совсем в тему

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/CommentNewDto.java
> +public class CommentNewDto {
зачем иметь две Dto для коментариев, если можно использовать одну со всем полями, и те которые не нужны будут просто null

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    public static List<UserDto> toUserDto(Iterable<User> users) {
Аналогично с другими мапперами

2023-05-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    boolean canNotUpdate(Long userId, String email);
очень странно смотрится этот запрос, почему бы просто на урвоне сервиса не получить по email пользователя и сделать там проверки

2023-05-19 11:01 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/exceptions/ErrorMessage.java
> +    private String error;
Согласен.
https://www.baeldung.com/rest-api-error-handling-best-practices
Но,  в данном случае нет необходимости в этом.

2023-05-19 11:23 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    boolean canNotUpdate(Long userId, String email);
Возможно странно. Но мне захотелось реализовать именно такой вариант.
Единственное, какое то время пришлось искать то как вернуть boolean использую JPQL (без нативного запроса).
К тому же у меня под данный метод в прошлом спринте при InMemory реализации были JUnit тесты написаны. Хотя как сказал наставник их можно было до 15 спринта вообще не писать.

2023-05-19 11:52 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static Booking toBooking(BookingNewDto bookingNewDto, Item item, User user) {
Спасибо.
Ваш вариант мне больше нравится.
В теории (в примере) был такой вариант: UserMapper.mapToUserDto ,  на мой взгляд избыточно.
Хотя в таком варианте с трудом представляю как написать 
public static ItemBookingDto toItemBookingDto(
            Item item, BookingShort last, BookingShort next, List<Comment> comments) {
Оставил как есть.

2023-05-19 11:53 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static List<BookingDto> toBookingDto(Iterable<Booking> bookings) {
Исправил.

2023-05-19 12:06 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByBooker_IdOrderByStartDesc(Long bookerId);
Везде исправил.
IDEA выдает и вариант с подчеркиванием и без. 
Воспользовавшись поиском нашел :
Из документации по spring (https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-property-expressions) вариант с подчеркиванием приемлем, но в другом случае.

2023-05-19 12:22 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllBookings(Long userId, State state, boolean isOwner) {
Исправил

2023-05-19 12:25 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/booking/State.java
> +    public boolean equal(String paramState) {
Спасибо. Удалил. (Забыл удалить :)

2023-05-19 12:26 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/booking/StateConverter.java
> +public class StateConverter implements Converter<String, State> {
Удалил.

2023-05-19 12:31 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +public class PersistenceConfig {
Удалил. Когда начинал кодить по этому спринту, была проблема с транзакцией. И @EnableTransactionManagement помогла тогда. Сейчас все работает без нее. (Странно, не помню, что точно было.)

2023-05-19 12:31 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +    public static CommentDto toCommentDto(Comment comment) {
Усправил.

2023-05-19 12:32 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> findCommentsByItem_IdOrderByCreatedAsc(Long itemId);
Исправил. Выше написал.

2023-05-19 12:41 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private Set<BookingStatus> getIn() {
Исправил.
Изначально был метод getNotIn() для другого метод который исключал три 3/4 enum-а, потом он эволюционировал до getIn, но не-до-эволюционировал.

2023-05-19 12:54 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<BookingShort> lastList = bookingRepository.getLastBooking(itemId, userId,
В JPQL limit проблематично использовать, а native query я принципиально не использовал.
Поискав:
https://en.getdocs.org/jpa-limit-query-results/
https://stackguides.com/questions/1239723/how-do-you-do-a-limit-query-in-jpql-or-hql
https://en.getdocs.org/jpa-limit-query-results/

Выбрал такой. Мне показалась он больше подходит под аннотацию @Query

А в методе сервиса: addComment
Сделал через Page<>, код даже приятней чем с List<> реализацией выглядит выглядит.

2023-05-19 12:55 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<BookingShort> nextList = bookingRepository.getNextBooking(itemId, userId,
Выше написал

2023-05-19 13:01 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/dto/CommentNewDto.java
> +public class CommentNewDto {
Хотел использовать один, но решил попробовать CommentNewDto  и столкнулся с такой проблемой:
https://app.pachca.com/chats?thread_id=1083870
Разобрался. (хотя до сих пор не разобрался с таким поведение) поэтому решил оставить как есть.

2023-05-19 13:01 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    public static List<UserDto> toUserDto(Iterable<User> users) {
Исправил

2023-05-20 10:47 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static Booking toBooking(BookingNewDto bookingNewDto, Item item, User user) {
это все вкусовщина и зависит от проекта, поэтому имя может быть хоть мегадлинное, главное чтобы это всех устраивало

2023-05-20 10:51 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exceptions/ErrorMessage.java
> +    private String error;
в гите не так удобно за счет того что нельзя комментарий пометить как необязательный к исправлению
тут больше коментов с прицелом на то, что просто есть другой подход

2023-05-20 10:52 UTC, TomattmanYandex approved these changes
Принято

2023-05-20 10:58 UTC, merged