Add item requests
zg-devj/java-shareit pull request #3
Opened 2023-05-31 10:53 UTC by zg-devj

2023-06-01 07:19 UTC, TomattmanYandex requested changes
Привет, отличная работа, замечаний только парочка
ну и по тестам парочка, коментарии только в одном примере, но это же стоит глянуть в остальных

2023-06-01 07:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        State state1 = checkState(state);
state стоит проверять на урвовне сервиса

2023-06-01 07:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>          userIsNull(userId);
я бы все эти проверки делал на уровне сервиса

2023-06-01 07:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    private LocalDateTime created = LocalDateTime.now();
еще вариант, на уровне базы сделать значение по умолчанию

2023-06-01 07:19 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    void test_getAllBookingsForOwner() {
стоит вынести подготовку данных в отдельный метод а потом сделать кучку маленьких методов на проверку каждого из кейсов (каждого из состояний)
это будет лучше за счет того, что если сейчс если приложение упадет на первой проверке то остальные не будут выполнены,  а если сделать отдельный тест для каждого случая, то будут выполнены все проверки, и будет более наглядная картинка

Также добавь пожалуйста больше тестов, не только на получение, но и на сохранение и апдейт

2023-06-01 07:19 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    void test_getAllBookingsForOwner() {
обычно на каждый метод добавляют мин7имум по одному тесту, а обычно даже больше, чобы проверить множество условий

2023-06-01 08:22 UTC, zg-devj commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    void test_getAllBookingsForOwner() {
2. По поводу множественных условий.
Это проверяется в более узких тестах (модульных) сервисах (контролерах, репозиториях если в них есть ветвления). Зачем в интеграционных тестах делать такие нагрузочные проверки с ветвлением (с использованием  @SpringBooTest)!?
В теории яндекса об этом мало информации.
Вот здесь на мой взгляд очень не плохо изложена теория: https://www.arhohuttunen.com/spring-boot-integration-testing/
Цитат: "Мы должны использовать более широкие тесты, чтобы дать нам уверенность в том, что наше приложение работает правильно. Однако мы не должны тестировать условную логику или граничные случаи в этих тестах. Убедитесь, что более широкие тесты охватывают только то, что не могут охватить более узкие тесты."
Там же цикл статей по тестированию (на мой взгляд просто отличный) : https://www.arhohuttunen.com/spring-boot-testing-tutorial/

2023-06-01 09:05 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    private LocalDateTime created = LocalDateTime.now();
Спасибо, про такой вариант забыл.

2023-06-01 10:33 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        State state1 = checkState(state);
Исправил.
Но метод сервиса теперь выглядит теперь так : getAllBookings(long, String, int, int), и все таки State (А по сути оно State а не String) выглядел бы белее логичней. Но это мое мнение.

2023-06-01 10:47 UTC, zg-devj commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>          userIsNull(userId);
Оставил, т.к. проверяю переменную на null, а не самого пользователя. проверка пользователя в сервисе.
у метода сервиса изменил Long на long.

2023-06-01 11:40 UTC, zg-devj commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    void test_getAllBookingsForOwner() {
1. 
-  Т.к. используется @Transactional, то если какой-то тест падал, остальные отрабатывали нормально.

2023-06-02 10:00 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    void test_getAllBookingsForOwner() {
согласен
если есть покрытие узких мест в юнит тестах то в интеграционных достаточно проверить только взаимодействие между слоями, 
просто очень часто разработчики ну очень не любят писать тесты, и иногда, добавляют например только интеграционные тесты, и тогда они должны покрывать и граничные условия тоже.
А тут добавил этот комментарий потому что основная часть этой работы это  как раз тесты, и наличие множества разных, это больше как пример того как надо тестировать, 
Например, я обычно не сталкиваюсь с тестами репозиториев, и если надо протестировать репозитории, то обычно обхожусь интеграционным тестом, который будет задействовать какой то функционал с уровня репозитория.

2023-06-02 10:00 UTC, TomattmanYandex approved these changes
Принято

2023-06-02 10:07 UTC, merged