Add docker
zg-devj/java-shareit pull request #5
Opened 2023-06-13 11:24 UTC by zg-devj

2023-06-14 08:05 UTC, TomattmanYandex requested changes
Выглядит отлично, есть пара моментов которые можно глянуть

2023-06-14 08:05 UTC, TomattmanYandex commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private void validDateForBookingNewDto(BookingNewRequestDto bookingNewDto) {
Большая часть из этих проверок могла бы быть выполнена аннотациями валидации

2023-06-14 08:05 UTC, TomattmanYandex commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        userIsNull(userId);
почему бы просто не сделать хедер обязательными, а не проверять везде

2023-06-14 08:05 UTC, TomattmanYandex commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        userIsNull(userId);
аналогично

2023-06-14 11:35 UTC, zg-devj commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        userIsNull(userId);
Действительно лишняя проверка, оно по дефолту обязательно.

2023-06-14 11:35 UTC, zg-devj commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        userIsNull(userId);
Исправил

2023-06-14 11:39 UTC, zg-devj commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private void validDateForBookingNewDto(BookingNewRequestDto bookingNewDto) {
Исправил

2023-06-15 07:59 UTC, TomattmanYandex approved these changes
Принято

2023-06-15 10:31 UTC, merged